#############################################################################
# Makefile for building: christmasDefence.app/Contents/MacOS/christmasDefence
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  christmasDefence.pro
# Template: app
# Command: /Users/deserg/anaconda2/bin/qmake -spec macx-xcode -o christmasDefence.xcodeproj/project.pbxproj christmasDefence.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/deserg/anaconda2/bin/qmake
christmasDefence.xcodeproj/project.pbxproj: christmasDefence.pro ../../../anaconda2/mkspecs/macx-clang/qmake.conf ../../../anaconda2/mkspecs/features/spec_pre.prf \
		../../../anaconda2/mkspecs/qdevice.pri \
		../../../anaconda2/mkspecs/features/device_config.prf \
		../../../anaconda2/mkspecs/common/unix.conf \
		../../../anaconda2/mkspecs/common/mac.conf \
		../../../anaconda2/mkspecs/common/macx.conf \
		../../../anaconda2/mkspecs/common/sanitize.conf \
		../../../anaconda2/mkspecs/common/gcc-base.conf \
		../../../anaconda2/mkspecs/common/gcc-base-mac.conf \
		../../../anaconda2/mkspecs/common/clang.conf \
		../../../anaconda2/mkspecs/common/clang-mac.conf \
		../../../anaconda2/mkspecs/qconfig.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_concurrent.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_core.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_core_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_designer.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_designer_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_gui.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_gui_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_help.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_help_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_macextras.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimedia.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_network.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_network_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_nfc.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_opengl.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_printsupport.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qml.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qml_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qmltest.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quick.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quick_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_script.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_script_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_scripttools.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_sql.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_sql_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_svg.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_svg_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_testlib.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_uitools.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webchannel.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webengine.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_websockets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webview.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_webview_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_widgets.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xml.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xml_private.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../anaconda2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../anaconda2/mkspecs/features/qt_functions.prf \
		../../../anaconda2/mkspecs/features/qt_config.prf \
		../../../anaconda2/mkspecs/macx-clang/qmake.conf \
		../../../anaconda2/mkspecs/macx-xcode/qmake.conf \
		../../../anaconda2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../anaconda2/mkspecs/features/exclusive_builds.prf \
		../../../anaconda2/mkspecs/features/default_pre.prf \
		../../../anaconda2/mkspecs/features/mac/default_pre.prf \
		../../../anaconda2/mkspecs/features/resolve_config.prf \
		../../../anaconda2/mkspecs/features/default_post.prf \
		../../../anaconda2/mkspecs/features/mac/sdk.prf \
		../../../anaconda2/mkspecs/features/mac/default_post.prf \
		../../../anaconda2/mkspecs/features/mac/objective_c.prf \
		../../../anaconda2/mkspecs/features/warn_on.prf \
		../../../anaconda2/mkspecs/features/qt.prf \
		../../../anaconda2/mkspecs/features/resources.prf \
		../../../anaconda2/mkspecs/features/moc.prf \
		../../../anaconda2/mkspecs/features/unix/opengl.prf \
		../../../anaconda2/mkspecs/features/uic.prf \
		../../../anaconda2/mkspecs/features/unix/thread.prf \
		../../../anaconda2/mkspecs/features/mac/rez.prf \
		../../../anaconda2/mkspecs/features/testcase_targets.prf \
		../../../anaconda2/mkspecs/features/exceptions.prf \
		../../../anaconda2/mkspecs/features/yacc.prf \
		../../../anaconda2/mkspecs/features/lex.prf \
		christmasDefence.pro \
		qresource.qrc \
		../../../anaconda2/lib/libQt5OpenGL.prl \
		../../../anaconda2/lib/libQt5Widgets.prl \
		../../../anaconda2/lib/libQt5Gui.prl \
		../../../anaconda2/lib/libQt5Core.prl
	$(QMAKE) -spec macx-xcode -o christmasDefence.xcodeproj/project.pbxproj christmasDefence.pro
../../../anaconda2/mkspecs/features/spec_pre.prf:
../../../anaconda2/mkspecs/qdevice.pri:
../../../anaconda2/mkspecs/features/device_config.prf:
../../../anaconda2/mkspecs/common/unix.conf:
../../../anaconda2/mkspecs/common/mac.conf:
../../../anaconda2/mkspecs/common/macx.conf:
../../../anaconda2/mkspecs/common/sanitize.conf:
../../../anaconda2/mkspecs/common/gcc-base.conf:
../../../anaconda2/mkspecs/common/gcc-base-mac.conf:
../../../anaconda2/mkspecs/common/clang.conf:
../../../anaconda2/mkspecs/common/clang-mac.conf:
../../../anaconda2/mkspecs/qconfig.pri:
../../../anaconda2/mkspecs/modules/qt_lib_bluetooth.pri:
../../../anaconda2/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_clucene_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_concurrent.pri:
../../../anaconda2/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_core.pri:
../../../anaconda2/mkspecs/modules/qt_lib_core_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_designer.pri:
../../../anaconda2/mkspecs/modules/qt_lib_designer_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_gui.pri:
../../../anaconda2/mkspecs/modules/qt_lib_gui_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_help.pri:
../../../anaconda2/mkspecs/modules/qt_lib_help_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_macextras.pri:
../../../anaconda2/mkspecs/modules/qt_lib_macextras_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_multimedia.pri:
../../../anaconda2/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../anaconda2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_network.pri:
../../../anaconda2/mkspecs/modules/qt_lib_network_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_nfc.pri:
../../../anaconda2/mkspecs/modules/qt_lib_nfc_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_opengl.pri:
../../../anaconda2/mkspecs/modules/qt_lib_opengl_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_openglextensions.pri:
../../../anaconda2/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_printsupport.pri:
../../../anaconda2/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qml.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qml_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qmltest.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_quick.pri:
../../../anaconda2/mkspecs/modules/qt_lib_quick_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../anaconda2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_script.pri:
../../../anaconda2/mkspecs/modules/qt_lib_script_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_scripttools.pri:
../../../anaconda2/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_sql.pri:
../../../anaconda2/mkspecs/modules/qt_lib_sql_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_svg.pri:
../../../anaconda2/mkspecs/modules/qt_lib_svg_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_testlib.pri:
../../../anaconda2/mkspecs/modules/qt_lib_testlib_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_uiplugin.pri:
../../../anaconda2/mkspecs/modules/qt_lib_uitools.pri:
../../../anaconda2/mkspecs/modules/qt_lib_uitools_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webchannel.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webengine.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webengine_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webenginecore.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_websockets.pri:
../../../anaconda2/mkspecs/modules/qt_lib_websockets_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webview.pri:
../../../anaconda2/mkspecs/modules/qt_lib_webview_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_widgets.pri:
../../../anaconda2/mkspecs/modules/qt_lib_widgets_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_xml.pri:
../../../anaconda2/mkspecs/modules/qt_lib_xml_private.pri:
../../../anaconda2/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../anaconda2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../anaconda2/mkspecs/features/qt_functions.prf:
../../../anaconda2/mkspecs/features/qt_config.prf:
../../../anaconda2/mkspecs/macx-clang/qmake.conf:
../../../anaconda2/mkspecs/macx-xcode/qmake.conf:
../../../anaconda2/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../anaconda2/mkspecs/features/exclusive_builds.prf:
../../../anaconda2/mkspecs/features/default_pre.prf:
../../../anaconda2/mkspecs/features/mac/default_pre.prf:
../../../anaconda2/mkspecs/features/resolve_config.prf:
../../../anaconda2/mkspecs/features/default_post.prf:
../../../anaconda2/mkspecs/features/mac/sdk.prf:
../../../anaconda2/mkspecs/features/mac/default_post.prf:
../../../anaconda2/mkspecs/features/mac/objective_c.prf:
../../../anaconda2/mkspecs/features/warn_on.prf:
../../../anaconda2/mkspecs/features/qt.prf:
../../../anaconda2/mkspecs/features/resources.prf:
../../../anaconda2/mkspecs/features/moc.prf:
../../../anaconda2/mkspecs/features/unix/opengl.prf:
../../../anaconda2/mkspecs/features/uic.prf:
../../../anaconda2/mkspecs/features/unix/thread.prf:
../../../anaconda2/mkspecs/features/mac/rez.prf:
../../../anaconda2/mkspecs/features/testcase_targets.prf:
../../../anaconda2/mkspecs/features/exceptions.prf:
../../../anaconda2/mkspecs/features/yacc.prf:
../../../anaconda2/mkspecs/features/lex.prf:
christmasDefence.pro:
qresource.qrc:
../../../anaconda2/lib/libQt5OpenGL.prl:
../../../anaconda2/lib/libQt5Widgets.prl:
../../../anaconda2/lib/libQt5Gui.prl:
../../../anaconda2/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-xcode -o christmasDefence.xcodeproj/project.pbxproj christmasDefence.pro

qmake_all: FORCE

